In [1]:
import numpy as np

In [2]:
np.random.seed(10)

In [22]:
x = np.random.randint (1, 10, 5)
xm = np.mean(x)
print(x)
print(xm)

[3 1 7 8 9]
5.6


In [23]:
i = 0
arrx = []
while i < len(x):
    xp = x[i] - xm
    arrx.append(xp)
    i += 1
print(arrx)    

[-2.5999999999999996, -4.6, 1.4000000000000004, 2.4000000000000004, 3.4000000000000004]


In [27]:
zigma_x = np.sum(arrx)
print(zigma_x)

1.7763568394002505e-15


In [6]:
y = np.random.randint (1, 10, 5)
ym = np.mean(y)
print(y)
print(ym)

[9 1 9 7 5]
6.2


In [9]:
i = 0
arry = []
while i < len(y):
    yp = y[i] - ym
    arry.append(yp)
    i += 1
print(arry)    

[ 2.8 -5.2  2.8  0.8 -1.2]


In [31]:
zigma_y = np.sum(arry)
print(zigma_y)

-0.0


In [32]:
theta = ((zigma_x) * (zigma_y))/(zigma_x)**2
theta    

-0.5

In [33]:
c = y - theta * x
c

array([10.5,  1.5, 12.5, 11. ,  9.5])